"""Add Rating model for many-to-many

Revision ID: 564250659a9c
Revises: d318557bfc08
Create Date: 2025-11-12 11:49:34.425461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '564250659a9c'
down_revision = 'd318557bfc08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('joke_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['joke_id'], ['joke.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rating_score'), ['score'], unique=False)
        batch_op.create_index(batch_op.f('ix_rating_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rating_timestamp'))
        batch_op.drop_index(batch_op.f('ix_rating_score'))

    op.drop_table('rating')
    # ### end Alembic commands ###
