"""Add UserAction log table

Revision ID: a46099f59c98
Revises: 564250659a9c
Create Date: 2025-11-17 11:58:52.796124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a46099f59c98'
down_revision = '564250659a9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=True),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_action', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_action_action_type'), ['action_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_action_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_action', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_action_timestamp'))
        batch_op.drop_index(batch_op.f('ix_user_action_action_type'))

    op.drop_table('user_action')
    # ### end Alembic commands ###
